### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by alphapapa** [wasamasa/shackle#12]
I'm sorry if I'm just too much of an Emacs rookie, but I can't get Shackle to work at all.

```(setq shackle-rules '((help-mode :select t)))```

Then I do `C-h f RET` (using Helm), and a window for a help-mode buffer comes up.  But it's not selected.  I have to `C-x o` to select the window, and `C-x 1` to close it, as usual.

I've also tried ```(setq shackle-rules '(("*Help*" :select t)))```, but it still doesn't work.

I first tried using `customize` to configure it, but that didn't work either.

Am I doing something wrong?

Thanks.

**Comment by alphapapa** [comment]
I'm sorry, I made a really silly mistake.  It is working, it is selecting the window when it comes up.

The problem is that the window doesn't have the active-window background color until I `C-x o` away from it and back to it again.

Is this a bug in shackle or somewhere else?

Thanks.

**Comment by wasamasa** [comment]
What exactly is an "active-window background color"?

**Comment by alphapapa** [comment]
Ah, I'm sorry again.  I'm using `auto-dim-other-buffers-mode`, and I guess I've been using it for so long that I forgot it isn't built-in to Emacs.  The bug must be in that package.  Sorry for wasting your time.

**Comment by wasamasa** [comment]
I've checked with shackle disabled and it looks like a bug in auto-dim-other-buffers since commands popping to a window and selecting it directly afterwards (like, `M-x run-python` with `pop-to-buffer`) exhibit the same behaviour.

I'd usually recommend you to open an issue on the project's issue tracker, but assuming it's [this one](https://github.com/mina86/auto-dim-other-buffers.el/pulls) they don't have any issue tracker at all, just the option to hand in pull requests.

**Comment by alphapapa** [comment]
Thanks, I've already sent him an email just like you suggested.  :)
