### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by kaushalmodi** [wasamasa/shackle#16]
You have

``` el
(setq shackle-rules
      '((compilation-mode :noselect t)
        (t :select t)))
```

Should it be:

``` el
(setq shackle-rules
      '((compilation-mode :select nil) ; No keyword called :noselect
        (t :select t)))
```

**Comment by wasamasa** [comment]
Both result in the same behaviour.  This is because once a rule is picked, no other rule's actions (not even the default ones) are taken into account.  To make it more obvious that the mere purpose of this rule is not selecting compilation windows, I'm using a non-existent key here.

FWIW, all of this is codified in the following sentence from the README:

>To have an exception to a fallback rule, use the condition of your choice and either don't list the key-value pair, use a different value or use a placeholder key with any value.
