### ISSUE TITLE
shackle-mode breaks helm completion of M-: with :same t

### ISSUE THREAD

**Issue by IvanMalison** [wasamasa/shackle#27]
I suspect that this is because helm wants to run in a buffer that is not the mini buffer and shackle is not allowing this.

Perhaps this makes sense/is desired behavior/another setting should be used, but I could see an argument that :same should not affect behavior from the mini buffer

EDIT: I suppose it wouldn't be too hard to write a custom rule for this...

**Comment by wasamasa** [comment]
Assuming `emacs -Q`, `(setq shackle-default-rule '(:same t))` and `(setq shackle-rules '(("*Backtrace* :popup t)))` I can reproduce the problem in two different ways:

1. Only one window open:

`display-buffer` is run and with the given Shackle settings the minibuffer window stays selected.  Helm ends up calling `delete-other-windows` from `helm-update` for whatever reason and this fails because that would maximize the minibuffer which just isn't possible to do.

2. More than one window open:

Helm doesn't error out (nearly) immediately and proceeds to its completion prompt. A subsequent press of `TAB` yields an error because Helm expects a window to have been popped up, but didn't check whether there was any.

---

Weren't it for the second case, I'd consider adding a check for the minibuffer that figures out a suitable window (probably by grabbing a list of all windows sans minibuffer, then looking for the most recently used one).  But given the second case, I'd rather advise you to add an exception for Helm:

```elisp
(setq shackle-rules '(("\\`\\*helm-mode-.*?\\'" :popup t :regexp t)))
```

**Comment by IvanMalison** [comment]
I don't necessarily want an exception for helm. I'd really only want the exception if I am in the minibuffer. I suppose that I can give this a shot though. Thanks for your help.
