### ISSUE TITLE
Default lighter is unable to be displayed in official GUI Emacs on OS X

### ISSUE THREAD

**Issue by xuchunyang** [wasamasa/shackle#29]
I think some special character is in that lighter string

**Comment by wasamasa** [comment]
That's right. Emacs is pretty much a failure at this, even if the necessary fonts do exist (which I'm pretty sure of on OS X), simply because it doesn't really do font fallback: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20727

This will be "fixed" in Emacs 25.1 if you happen to have the Symbola font installed.

You can alternatively customize `eyebrowse-lighter` or your default fontset if you know a font to work as fallback.  I've blogged about how one would do this and other frame hackery: http://emacsninja.com/posts/who-framed-emacs.html
