### ISSUE TITLE
Feature request: width/height settings

### ISSUE THREAD

**Issue by hlissner** [wasamasa/shackle#32]
First off, thank you for shackle. Popwin's been a bad itch for years and emacs feels _much_ snappier without it.

Anyhow: one thing I miss from popwin are `:height` and `:width`, would you consider adding them? Either as a fall-through on `:ratio` when N > 1 (was mentioned in #8) or as separate keys. I'd be happy to do a PR for it myself if you prefer.

A ratio size is uncomfortable working across systems with drastically different resolutions like I do (2560x1600 at home and 1280x800 away from home). I also don't think a ratio is meaningful for some windows (like the 2-3 line popups org-link or org-todo throws up).

**Comment by wasamasa** [comment]
Thanks for the reminder.  I believe this to be an useful addition.

Not sure on whether to keep using `:ratio` (that way I could just reuse the code handling it and extend it to do the right thing) or `:height`/`:width` (which would be more meaningful names, but are two new keys instead of one handling all alignments).  Perhaps `:size` would be a better solution?

Regarding the semantics, I assume that an aligned window would use a specified size or a specified ratio or the default ratio, correct?  Or can you envision a default size to make sense in this context?

**Comment by hlissner** [comment]
I think `:size` would be the simplest. Treat N < 1 as a ratio and N >= 1 as a fixed number of either lines or columns depending on `:align`.

As for the default size, I'd suggest renaming `shackle-default-ratio` to `shackle-default-size` (perhaps alias one to the other for backwards compatibility). Then an aligned window, lacking a specified `:size`, can fall back on `shackle-default-size`.

And, I see no problem leaving `shackle-default-size` with the default value of `0.5`

**Comment by wasamasa** [comment]
Oh, so you've thought of renaming `:ratio` to `:size` and making it handle non-float values as well?  That would indeed solve the problem of not having defaults for that case, albeit at the cost of a bit more backwards-compatibility code.

**Comment by hlissner** [comment]
That would be ideal, though I see no problem with keeping both (purely for backwards compatibility), even if both accept the same values.

**Comment by hlissner** [comment]
Just got around to using it and it works great! Thanks!
