### ISSUE TITLE
C-g as popwin

### ISSUE THREAD

**Issue by joca-bt** [wasamasa/shackle#8]
I've been experimenting with ```shackle``` and ```popwin```. Although I prefer ```shackle```, there's a feature I really miss, which is the closing of the temporary buffers with ```C-g``` or the other ```popwin``` rules. I think this would be a great addition to ```shackle```.

**Comment by wasamasa** [comment]
I don't want to implement `C-g` for closing windows since the only way of making it work the way it does in `popwin` is using timers (or in other words, checking over and over again with very small waiting windows aka polling). If you do this in `popwin`, you eventually get lots of timers that don't stop running out which leads to other problems like your cursor flickering for no apparent reason.

I'm not sure what you mean with "the other `popwin` rules". Are you speaking of [this docstring](https://github.com/m2ym/popwin-el/blob/70939ccb563e7df4a2e247d6ff806f8334d27449/popwin.el#L741-L783)?

**Comment by wasamasa** [comment]
Well, since I've recommenced hacking on popwin, I've decided to revisit that particular docstring I suspect you're refering to:

- `regexp`: Implemented already.
- `width`, `height`: Not implemented, I went for a ratio keyword instead.  If there is demand for it, I could make that keyword more magic by interpreting it as a number of lines whenever it's larger than 1. Alternatively implementing a different keyword as its counterpart would work as well.
- `position`: Implemented already.
- `noselect`: I've implemented a selection keyword instead since that posed less issues and did look better in the ruleset than the negation. In other words, `noselect` is on by default.
- `dedicated`: Not implemented. I have no idea what the hell this is supposed to do.
- `stick`: Not implemented. I have no idea what this is supposed to do either.
- `tail`: Not implemented. I can guess what this is supposed to do, but it sounds rather niche considering the only usecases where I'd expect it to do anything useful (like, the `*Messages*` buffer or the compilation buffer) do already start out with point at their end, so the only thing it would do would be recentering them every time you view them.

As for the other raised issue, it could be possible to do something with a function in `post-command-hook` that checks whether the last command was `keyboard-quit'. However, it wouldn't make much sense since there is nothing to quit from in `shackle` since unlike `popwin` it does not have its own popup window replacing all popups and just modifies the buffer display machinery slightly. Again, I'd be thankful if you could go into more detail in case my assumptions should be wrong.

**Comment by usharf** [comment]
"dedicated" is a flag that should prevent emacs from selecting files into a particular window. Would be nice to support IMHO. Windows can be marked dedicated `set-window-dedicated-p`, or using this minor mode [dedicated.el](https://github.com/jwiegley/dot-emacs/blob/master/site-lisp/dedicated.el).

**Comment by wasamasa** [comment]
That's what one would assume since everything else in Emacs uses the word that way, however the docstring says something entirely different:

> If the value is non-nil, the popup window will be dedicated to the original popup buffer. In this case, when another buffer is selected in the popup window, the popup window will be closed immedicately and the selected buffer will be shown on the previously selected window.

The last sentence is especially puzzling and makes no sense to me.

**Comment by usharf** [comment]
You're right! 
PS and I don't understand either what they mean :(

**Comment by joca-bt** [comment]
Sorry for the delay, I meant [this](https://github.com/m2ym/popwin-el/blob/70939ccb563e7df4a2e247d6ff806f8334d27449/popwin.el#L516-L524).

**Comment by wasamasa** [comment]
OK, that explains it a bit more, but still sounds wrong since it subverts the whole benefit of marking a window as dedicated. Therefore, I will not implement it.

My previously listed issues with the `C-g` specific feature still apply.  First of all, it overloads a very important and special-cased keybinding, second it's impossible to implement it exactly the same way as popwin since the entire architecture is different.  All `shackle` does is popping a buffer differently than usual, after that's done its job is done, too. `popwin` on the other hand has a special buffer for itself associated with a window it resurrects every time, therefore an action to hide its window makes a lot more sense for it.  The best I could do is writing up a generic command that quits the window if appropriate or alternatively just buries the buffer, then uses it in the post-command hook on a popped up window. Another reason I'm reluctant to add support for it is because this very action can be triggered in nearly every special buffer by hitting `q`.

**Comment by joca-bt** [comment]
Yep, ```(setq shackle-rules '((t :select t)))``` and ```q``` pretty much do the job.

However, could we track down if the last differently pop'ed buffer is still visible and do stuff to him? That should do, no?

**Comment by wasamasa** [comment]
There isn't anything recording the last buffer popped up.  The `:select` keyword for instance does only check for the window opened of the buffer that was displayed and selects it if it's still alive.

What exactly would you want to do with that information if it were available? Writing a command that quits the window for you or buries the buffer if it's the only window?

**Comment by joca-bt** [comment]
For me, the most useful would be:
1) easily kill or bury the buffer from some other window if it is visible,
2) close or "maximize" that window it is visible.

I don't think navigation between pop'ed up buffers is very useful, like ```popwin``` has.

**Comment by wasamasa** [comment]
OK, if you wish to make use of such an exposed variable for writing your own commands to bind to a key, I can surely make it available for you.  Please confirm if that's all you need, then I'll push a commit and mark this issue as closed.

**Comment by wasamasa** [comment]
Bump.

**Comment by joca-bt** [comment]
Sorry for the late reply. I think that would be useful.

Are you talking about a variable pointing to the buffer and window just opened? However, when the buffer goes out of sight, it should be clear. I think there's no point in activating it again once it comes on-sight again.

**Comment by wasamasa** [comment]
Yes, I'm talking about that kind of variable. No, I don't have any idea how it's supposed to magically know when to clear itself.  It would be more sensible to do it the other way around and whenever using its value check whether there's a window visible using that buffer instead of cramming magic into it.

**Comment by joca-bt** [comment]
That way can't we run into situations in which a buffer that was shackle'd and no longer is, thinks it's still shackle'd?

We could add some buffer-local variable to the buffer when it is pop'ed up with shackle to keep track of its display origin and advice/hook the relevant window/buffer display operations to reset the values for such buffers. What do you think?

**Comment by wasamasa** [comment]
These situations would happen whenever inspecting a buffer you've switched away from by switching to it a second time. They wouldn't happen for window quitting since that deletes the window which won't appear ever again.  I've tried reliably detecting such buffer switches with restricted hooks, but failed at triggering them exactly once, so no, I'm not too keen on attempting to do this again.

On the other hand tracking the last popped window and last buffer could work.  Since quitting would change both currently visible windows and selected buffers and switching would make the selected buffer not correspond with the still living window anymore, you could discern that change easily without any need to reset.

**Comment by joca-bt** [comment]
Yeah, that seems like it would do it.

**Comment by wasamasa** [comment]
I've implemented it for aligned windows and popup windows for the time being because the frame, reuse and switch options don't make sense with it.

**Comment by joca-bt** [comment]
Thanks, I will give it a try.

**Comment by hydandata** [comment]
I am using something like this:

```elisp
;;; Make C-g delete current window if it is not the sole one and not
;;; minibuffer either
(defun close-this-window ()
  "Unless the currently active window is a minibuffer or a sole
  active window, delete it."
  (let ((this-window (get-buffer-window (current-buffer))))
    (unless (or (one-window-p) (window-minibuffer-p this-window))
      (delete-window this-window))))

(advice-add 'keyboard-quit :before 'close-this-window)
```
It is not specific to shackle in any way, and definitely a bit unorthodox, but it gets the job done for me.

**Comment by wasamasa** [comment]
Hm, this should be roughly equivalent to hitting `ESC ESC ESC` which calls `keyboard-escape-quit`.  Did you try adding that as advice?

**Comment by hydandata** [comment]
That seems to do `delete-other-windows` not delete the currently active one.

**Comment by wasamasa** [comment]
Oh, right.

**Comment by hydandata** [comment]
Forgot to mention that this only makes sense when you have `:select t` for everything and also that `quit-window` works as a substitute for `delete-window` if one so desires.
